### ISSUE TITLE
Auto Group - Auto Cooldowns not displaying

### ISSUE THREAD

**Issue by coachseat** [Dicebar/Raven#81]
Other bar groups appear to be working, but Auto Cooldowns won't show. Have attempted to create new bar group, and double checked all visibility settings.

**Comment by Dicebar** [comment]
Thanks for the report, I'll have a look!

**Comment by Dicebar** [comment]
I think the issue should be solved with `r666`. Can you test and confirm?

Note that GH-79 still applies and Raven_Options is missing from the release.

**Comment by coachseat** [comment]
> I think the issue should be solved with `r666`. Can you test and confirm?
> 
> Note that [GH-79](https://github.com/Dicebar/Raven/issues/79) still applies and Raven_Options is missing from the release.

Solved!

**Comment by coachseat** [comment]
May need to open this again, it appears some cooldowns are properly tracked in auto group and some don't show up. I can give more info if needed!

**Comment by Dicebar** [comment]
> I can give more info if needed!

Please do! Which work, which don't?

**Comment by coachseat** [comment]
Tested across a few characters, looks like things with more than one charge, or that could have more than one charge via talents, don't display, i.e.

Rogue -- Feint, Shiv, Shadowstep, Vanish (Doesn't display despite not being talented into 2nd vanish charge)
Paladin -- Hammer of Wrath, Judgement (Flash of Light w/ cd via talent also doesn't display)
Priest -- Mind Blast

Looks like this is the trend! I'll post here if I find any that don't fit that pattern.

**Comment by Dicebar** [comment]
Excellent, thanks!

**Comment by Dicebar** [comment]
I think I fixed it with `r674`. Can you confirm?

**Comment by coachseat** [comment]
Looks good! Looks solved for all CDs that have more than one charge.

The paladin ability Flash of Light still doesn't display, but it also didn't on previous versions. Just a nitpick, the bigger concern is solved. Probably has something to do with the ability not having an inherent CD, but only getting one with the talent Light's Celerity chosen. Don't know offhand any other examples of this!

Thanks for the quick work!

**Comment by Dicebar** [comment]
There are actually a few spells like that. Ignore Pain for warriors, for example. I've made exceptions for those, I'll try to remember to add Flash of Light tomorrow.

**Comment by Dicebar** [comment]
The warrior ones actually no longer exist, apparently. I added the cooldown for Flash of Light though.
